### ISSUE TITLE
Listadmin got a new upstream home back in 2016

### ISSUE THREAD

**Issue by solbu** [OpenMandrivaAssociation/listadmin#1]
Hi.

Just noticed that OpenMandrivas listadmin package uses the old URLs, which has not had activity since 2007.
I took over the project in decenber 2016 and moved it to Sourceforge, and the last version (2.73) was released today.
https://sourceforge.net/projects/listadmin/

It wold be nice if you updated the OMV package with the new release.

**Comment by AngryPenguinPL** [comment]
Thanks for info.
Package updated.
